name: qazando
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK (adjust version if necessary)  # Configura JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'  # Define o JDK 1.8
          distribution: 'adopt'

      - name: Build project
        run: mvn package  # Ajuste este comando para o seu projeto, se necessário

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: mvn test